#!/usr/bin/perl

# Pick up an environment variable and feed it to podman without putting it on the command line

my($params) = join ' ', @ARGV;
open(CMD, "| docker login $params") or die "Error: Can't run docker command: $!";
print CMD "$ENV{BUILDER_REGISTRY_PASSWORD}" or die "Error: Can't print to docker command: $!";
close(CMD) or die "Error: Can't close docker command: $!";

exit;
